### ISSUE TITLE
Occupancy grid for unbounded scenes

### ISSUE THREAD

**Issue by hturki** [KAIR-BAIR/nerfacc#181]
Thanks for the great library! I'm trying to understand how to use the new multi-level occupancy grid for unbounded scenes:

- In https://github.com/KAIR-BAIR/nerfacc/blob/e547490c41751365235f70dc22219375a276e0ea/examples/train_ngp_nerf.py I see that you're not using the unbounded sphere contraction at all, and instead just enlarging the scene bounds by a factor of 4 (```scene_aabb```). Is my understanding correct?
- The occupancy grid itself https://github.com/KAIR-BAIR/nerfacc/blob/e547490c41751365235f70dc22219375a276e0ea/examples/train_ngp_nerf.py#L150 seems to be using the non-expanded scene bounds (```aabb```). What's the reason for this discrepancy?
- The current occupancy grid code says that "For multi-res occupancy grid, contraction is not supported yet." - could you provide some intuition as to what would go wrong with UN_BOUNDED_SPHERE contraction?

**Comment by liruilong940607** [comment]
Hi!

The Occ Grid is defined with the base level aabb, which we call the region of interest (`roi_aabb`). And each level in the Occ Grid is with a 2x aabb larger than the previous one. 

https://github.com/KAIR-BAIR/nerfacc/blob/e547490c41751365235f70dc22219375a276e0ea/nerfacc/grid.py#L113-L118

The radiance field, however is defined with the true bounding box of the scene, which in this case should be the highest level aabb that the Occ Grid can cover, thus is 2 ** 4 = 16 times larger than the base aabb.

https://github.com/KAIR-BAIR/nerfacc/blob/e547490c41751365235f70dc22219375a276e0ea/examples/train_ngp_nerf.py#L125-L130

We simply did not support contraction for multi-res occ grid because they serve very similar purpose of supporting unbounded scene (though multi-res is not true unbounded). Implementation wise, occ grid with contraction will distort the space thus the ray traversal within it will not be straight line. This makes grid traversal inefficient. So we are gradually switching to the decision of not support contraction for the occ grid in the future. Empirically multi-res grid works much better than single-res grid + contraction.

**Comment by hturki** [comment]
Thanks for the context, this is very helpful. FWIW MERF (https://arxiv.org/pdf/2302.12249.pdf) proposes a modified contraction that does preserve straight lines:

![image](https://user-images.githubusercontent.com/868618/229277933-93027a44-0dd7-46bb-a8e6-b27709f0d4d1.png)
![image](https://user-images.githubusercontent.com/868618/229277942-699e0343-ca0a-433e-afeb-0d32b390e972.png)

It could be interesting to add to this repo. I might do so if I decide to go down this route.

**Comment by hoanhle** [comment]
@liruilong940607, thanks a lot for the repo. I'm still a little bit confused about the point of scaling the `roi_aabb` when samples outside of it won't be used anyway. Could you provide some intuition on this?

Here's the link for reference: https://github.com/nerfstudio-project/nerfstudio/issues/3405
