### ISSUE TITLE
Not cuda toolkit

### ISSUE THREAD

**Issue by aiyb1314** [KAIR-BAIR/nerfacc#208]
When I run the code using pycharm, I get the following error message: NerfAcc: No CUDA toolkit found. NerfAcc will be disabled.
, but it succeeds when using the command line.

**Comment by liruilong940607** [comment]
That sounds like you need to config pycharm where cuda is. I’m not familiar with pycharm though

**Comment by HL4214** [comment]
Hi, I solved the problem;
The possible cause is that the call function from subprocess library starts a new process, but when running the code using pycharm, the enviroment is different from the commond line so that "nvcc" can not find;

My solution is first run "echo $PATH" on the commond line and then add the PATH value to enviroment variables in  pycharm;

**Comment by HL4214** [comment]
> When I run the code using pycharm, I get the following error message: NerfAcc: No CUDA toolkit found. NerfAcc will be disabled. , but it succeeds when using the command line.

Hi, I solved the problem;
The possible cause is that the call function from subprocess library starts a new process, but when running the code using pycharm, the enviroment is different from the commond line so that "nvcc" can not find;

My solution is first run "echo $PATH" on the commond line and then add the PATH value to enviroment variables in  pycharm;

**Comment by botaoye** [comment]
> > When I run the code using pycharm, I get the following error message: NerfAcc: No CUDA toolkit found. NerfAcc will be disabled. , but it succeeds when using the command line.
> 
> Hi, I solved the problem; The possible cause is that the call function from subprocess library starts a new process, but when running the code using pycharm, the enviroment is different from the commond line so that "nvcc" can not find;
> 
> My solution is first run "echo $PATH" on the commond line and then add the PATH value to enviroment variables in pycharm;

It works, thanks a lot!

**Comment by yuchenlichuck** [comment]
me too

**Comment by yuchenlichuck** [comment]
I am still come cross the same problems

**Comment by dawnzyt** [comment]
> I am still come cross the same problems

just add
```python
env_list = os.environ['PATH'].split(':')
env_list.append('/usr/local/cuda/bin')
os.environ['PATH'] = ':'.join(env_list)
```
